---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: psql-backup-s3
spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: psql-backup-s3-container
              image: cpcwood/psql-backup-s3:latest
              envFrom:
                - configMapRef:
                    name: psql-backup-s3
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: psql-backup-s3
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: psql-backup-s3
                      key: POSTGRES_PASSWORD
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: psql-backup-s3
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: psql-backup-s3
                      key: AWS_SECRET_ACCESS_KEY
          restartPolicy: Never          
---